### ISSUE TITLE
When should a new developer (if they want to learn it) learn Python?

### ISSUE THREAD

**Issue by roxnlopez** [den-materials/wdi-orientation#10]
Long term, I want to go into data analysis or data visualization. But, when is a good time to learn it during my new career?

https://softwareengineering.stackexchange.com/questions/12189/how-do-i-learn-python-from-zero-to-web-development

https://medium.freecodecamp.com/what-programming-language-should-i-learn-first-%CA%87d%C4%B1%C9%B9%C9%94s%C9%90%CA%8C%C9%90%C9%BE-%C9%B9%C7%9D%CA%8Dsu%C9%90-19a33b0a467d

I asked Zach but he doesn't know anything about Python.

**Comment by ZebGirouard** [comment]
Dave Thomas has a very helpful rule of thumb for "when to learn another programming language", because the phrase "when you're comfortable in your current language" is true but difficult to measure.

He says, "When you are coding in a language, and something in the back of your head says, 'Wait, this isn't the right way to do this. I know a better way...', you can move on to another language."

We will teach Javascript very deeply and PHP deeply enough to make you dangerous in this course. I would avoid learning any other languages during this course to avoid confusion. After this course, though, I would use your better judgment based on what you are seeing in Built in Colorado job listings. If you feel that "I know a better way" in Javascript, but are seeing a lot of postings that excite you for Python, that's when I would start learning it.

I also make a habit of not coding in two different languages on the same day (HTML/CSS/JS doesn't count because they're so different). It's like speaking Portuguese and Spanish in the same conversation, they'll be so similar you'll make a lot of mistakes, and just different enough that those mistakes will break your code. By the same token, once you learn Spanish really well, you can learn Portuguese in a couple months, it's just a matter of "what's different"--same thing with coding languages once you get the first one down solidly.  So if you're going down the Python route, I'd say dive in for full days based around a project idea you're psyched about.

Did that answer your question?

**Comment by roxnlopez** [comment]
I'm stoked to be dangerous. I'm going to throw that around now. Thanks for the help, Zeb! I do not plan on trying to learn anything further for a bit. So good to know for the future.
