### ISSUE TITLE
How do you research the different JS frameworks to find the right one to use?

### ISSUE THREAD

**Issue by SpindleMonkey** [den-materials/wdi-orientation#16]
I've found the following:
1. https://medium.com/@ZombieCodeKill/choosing-a-javascript-framework-535745d0ab90
2. https://stackoverflow.com/questions/25152506/benefits-and-drawbacks-of-using-client-side-frameworks
3. https://blog.appdynamics.com/product/comparing-the-4-most-popular-client-side-javascript-frameworks/
4. https://hackernoon.com/5-best-javascript-frameworks-in-2017-7a63b3870282

So these articles cover several frameworks, but how do you know if you're looked at the best frameworks for your application? Maybe what I really need to know is who should I trust for framework info?

**Comment by ZebGirouard** [comment]
In my opinion, often too much emphasis is placed on finding the best framework to solve a specific problem.  This is probably the most important part of choosing a framework, but an often-ignored close second is "what are you familiar with, and how similar is that to this new framework you're going to learn?"

If I were deciding between React and Angular, for instance, I'd need to know how familiar my team and I are with JSX (React), Typescript (Angular), State Management (React), Observables (Angular), ....

Next, I'd think about that important part of "what am I building?"  I usually google for good tutorials solving close to my problem like "Angular Email Forwarding App".  I measure quantity (10 google results from distinct sources is better than 2) and quality (try one of each of the tutorials...often these tutorials have out-of-date or unclear directions, follow your gut on which one is more comfortable).

*Everyone* is biased when it comes to frameworks, which can be frustrating, but once you find something you're comfortable with, stick with it for a while, rather than jumping between frameworks and their feature releases.

Something that's well worth looking at is [TodoMVC](http://todomvc.com/), which has an identical Todo app, built in all the most popular frameworks.

Did that answer your question?

**Comment by SpindleMonkey** [comment]
It does--that link is great & I've bookmarked it for the future when I'm asking this question again ;)
