### ISSUE TITLE
Working Remotely

### ISSUE THREAD

**Issue by jeffDevelops** [den-materials/wdi-orientation#17]
I think it would be really cool to travel while working remotely, and it seems like a possibility as long as you have an internet connection and some independence as a developer. How much experience could one expect to accrue before such a job arrangement is possible? It's a pretty relative question, dependent on the developer in question, the company they're working for, but what other factors come into play? Are you pretty much only destined to freelance if you take this route? I found these two resources pretty helpful, but personal narratives are always appreciated. 

Survey data (percentage of people that work remotely), etc.:
https://insights.stackoverflow.com/survey/2016#work-job-priorities

Personal experiences from random strangers on Quora:
https://www.quora.com/How-is-life-as-a-web-developer-who-works-remotely

I didn't talk to anyone for this Github issues example, but I'm aware that I need to should I need to submit an issue. :)

**Comment by nickandersonr** [comment]
Hey Jeff!

A very good question - lots of future devs want this lifestyle. 

First and foremost, you need a good amount of experience and proven quality work in order to freelance - remotely or otherwise. Freelance contracts generally come from previous connections in the industry, so starting out as one can be very difficult. After almost a decade, I'm at a point where I can find freelance work within a month or two, but it's a fulltime job just managing that pipeline.

If you want to freelance remotely, the other big factor is trust. I've never hired a remote dev that someone didn't personally vouch for, and I certainly wouldn't hire someone I didn't know with very little experience. 

If you can get a fulltime contract gig (as opposed to a single project), the rules might be a little different. Also, many companies might allow you to work from home, or from another city, once they've learned they can trust you. A developer at my last agency moved to Tennesse for his wife's job, but kept his job and worked remotely - because the dude was a total badass. Once you prove yourself, you should be able to start negotiating deals like that one.

Does that answer your question?

**Comment by jeffDevelops** [comment]
Yes, it does! Thank you!
