### ISSUE TITLE
How many/what programming languages should a freelance dev be very proficient in?

### ISSUE THREAD

**Issue by luluwelborn** [den-materials/wdi-orientation#18]
In the eyes of potential employers, is my/our time best spent being a jack of all trades or a master of a few?

Lot's of different opinions:
https://www.quora.com/What-are-the-best-programming-languages-to-learn-in-order-to-become-a-freelance-programmer
https://www.quora.com/For-an-average-programmer-how-many-programming-languages-should-he-she-be-very-proficient-in
http://www.codingdojo.com/blog/how-many-programming-languages-should-i-learn/

My online dev friend Farshad says to pick any of the popular programming languages and learn it well.

**Comment by ZebGirouard** [comment]
I agree with your friend.  Dave Thomas has a very helpful rule of thumb for "when to learn another programming language", because the phrase "when you're comfortable in your current language" is true but difficult to measure.  

He says, "When you are coding in a language, and something in the back of your head says, 'Wait, this isn't the right way to do this.  I know a better way...', you can move on to another language."

We will teach Javascript very deeply and PHP deeply enough to make you dangerous in this course.  I would avoid learning any other languages during this course to avoid confusion.  After this course, though, I would use your better judgment based on what you are seeing in [Built in Colorado](http://www.builtincolorado.com/) job listings.  If you feel that "I know a better way" in Javascript, but are seeing a lot of postings that excite you for Python, that's when I would start learning it.  But again, add those pieces one at a time, and don't move on to another language until you feel some comfort.

I also make a habit of not coding in two different languages on the same day (HTML/CSS/JS doesn't count because they're so different).  It's like speaking Portuguese and Spanish in the same conversation, they'll be so similar you'll make a lot of mistakes, and just different enough that those mistakes will break your code.  By the same token, once you learn Spanish really well, you can learn Portuguese in a couple months, it's just a matter of "what's different"--same thing with coding languages once you get the first one down solidly.

Did that answer your question?

**Comment by luluwelborn** [comment]
That thoroughly and wonderfully answered my question. Thanks!
