### ISSUE TITLE
javascript - i screwed up my prework memory game project

### ISSUE THREAD

**Issue by samascher** [den-materials/wdi-orientation#3]
i screwed up prework flip feature on the cards. 

checked out this website where you can literally input details about how you'd like the card(s) to flip and it generates HTML CSS and JS code for you

http://pingmin-tech.com/flipcardjs 

next i checked out the following site which contains the code for a memory game (he also links to a working demo) 

http://callmenick.com/post/memory-game

morning of 26 July (first day of class) - zebb suggested I talk to Stefan about this - i'm planning on doing so today to resolve.

**Comment by alexliinc** [comment]
This is awesome!!

**Comment by ZebGirouard** [comment]
Hi @samascher , this is a really cool find.  Nick will talk about Cargo Culting and using other people's code soon, but I'd just make sure to keep to using just a couple lines of code at a time so that you understand what the code is doing.  Otherwise, have at it.

If anything breaks, let Stefan or me know.
