### ISSUE TITLE
Front end/ back end or Full stack Dev 

### ISSUE THREAD

**Issue by Mazkid21** [den-materials/wdi-orientation#5]
Are there more front end / back end developers or are most moving to full stack 

https://techcrunch.com/2014/11/08/the-rise-and-fall-of-the-full-stack-developer/

https://medium.com/coderbyte/a-guide-to-becoming-a-full-stack-developer-in-2017-5c3c08a1600c

each site contradicted one another 

Asked Roxanne

**Comment by ZebGirouard** [comment]
This is an excellent question.  I would apply the same logic to this as I do most every other job:

You want *literacy* in the areas of all co-workers/collaborators you interface with.  *Expertise* in those areas, however, holds little value unless you are also their backup in case they are sick, leave the company, etc.  Front-end developers who do not understand how to set up a database are very difficult to converse with on full-stack projects.  By the same token, back-end developers who don't know CSS best practices like class-based CSS or using external stylesheets, are also difficult to converse with.

True full-stack developers are rare outside of small companies, but a common phrase in tech companies is a "bus number" or "truck number", i.e. "how many people need to get hit by a bus for our tech projects to come to a complete halt?"  In a company of about 50 people, 1 is a BAD number, 3 might be a good number, but something like 10 would actually mean everyone is overqualified for their jobs.  

You will specialize, no matter what.  So follow that path of least resistance that is a combination of job listings you see and things you enjoy.  

But don't forget to be a good sounding board and support network for your coworkers, who work on other parts of the stack.  That will probably mean doing a tutorial on the topic, or, better yet, having a real, deep conversation about the thing they work on because they are probably more than happy to spread their knowledge.

Did that answer your question?

**Comment by Mazkid21** [comment]
It did, thank you!
