### ISSUE TITLE
growing vs dying languages?

### ISSUE THREAD

**Issue by RettBehrens** [den-materials/wdi-orientation#6]
Which 3 languages do you personally believe demand will grow the most for in the coming years and which 3 languages do you think are overrated / on the way out?

http://www.codingdojo.com/blog/9-most-in-demand-programming-languages-of-2016/
https://insights.stackoverflow.com/survey/2016

I found some insight with these links, just looking for personal opinion / experience as well.

**Comment by ZebGirouard** [comment]
Phew, I will try to qualify my answer as much as possible, and encourage looking at online sources often, because these things change quickly, and I'm a fan of real data.  The TIOBE index is one I refer to often:

https://www.tiobe.com/tiobe-index/

As it says, "The ratings are based on the number of skilled engineers world-wide, courses and third party vendors. Popular search engines such as Google, Bing, Yahoo!, Wikipedia, Amazon, YouTube and Baidu are used to calculate the ratings."

This provides an answer for your second question, but unfortunately only clearly lists 2, not 3.  The good news is this matches with Nick and my experience as well.

Java and C are dying...but they are still at the top.  Java is not dying as fast as it could, mostly because of Android development.  C is not dying as fast as it could, mostly because of embedded devices and its cousins Objective-C (iOS development) and C++ (video game and windows app dev).  If any of these things interest you, you may want to give them a second look, otherwise I feel that you should only study them as a way to broaden your mind, and understand where we came from in development.  To clarify, I have built apps in these languages, and have a very basic foundation in them--I believe this is *very* useful, but I would only go deeper if you're going into the fields above.

Now for the picking the winner question, which is much harder.  I will sort them in order of decreasing confidence (i.e. feel pretty good about #1):

1) Javascript won the front-end, it just *is* the language of browsers now.  It is in the same position Java was 15 years ago.  Anyone talking about how great Haskell or oCaml is...any time they want to make a web app, they transpile to Javascript.  Cutting out that middle man is not essential, but is helpful.  Also ES6 has "solved" a lot of the things that scared other developers away from JS, and positioned the language as an incredibly performant, web-specific language.  It handles asynchronous actions (like page or image loading) and multithreading (doing tons of things independently) very well now, and basically all back-to-front-end data communication now is in JSON form.  What does the JS stand for there?  Yup, Javascript is everywhere.

2) .NET is making a serious comeback, but almost all of that growth is being driven by Microsoft.  It is a very strong horse, but I am hesitant that this growth can last cuz it has a single point of failure.

3) Go is showing itself as a legitimate player, not just a hobbyist's dream.  Again, though, almost all of that growth is driven by Google and Google fanboys, so I am not sure if it will continue to grow (or even evolve into another language).

Now, I'll give my very basic experience in other languages you will likely come across.  I'm only picking "winners" or "near-winners", because I highly recommend only learning one language at a time, and there's just too many out there.

PHP: Dying very slowly, because it came out slightly before JS, and was neck-and-neck for a long time with it.  Also, ALL Wordpress sites run off PHP and that's 25% of websites.  There will be lots of jobs in PHP at least for the next couple years.

Python: Growing very slowly, and has become the winner for any data analysis or web scraping.  There will be lots of Python jobs at least for the next couple years.

Ruby: Dying slowly, and hangs its hat only on Ruby on Rails, which is still a very popular option for start-ups, but is falling out of vogue everywhere else.  There will be lots of RonR jobs for the next couple years, but I feel like entry-level jobs are scarce, and I am doubtful of its future after 2 or 3 years from now.

Did that answer your question?

**Comment by RettBehrens** [comment]
Yes, thank you. Very informative!
